### PR TITLE
Upgrade to Terraform 0.12 SDK

### LINKED ISSUE #6: Error: Failed to instantiate provider "jenkins" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
I encountered Error: Failed to instantiate provider "jenkins" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5] when running terraform plan. Below is the terraform version we are using.
Terraform v0.12.24
+ provider.jenkins (unversioned)
+ provider.tfe v0.16.0

I installed the provider with "go install github.com/taiidani/terraform-provider-jenkins" and copy it to terraform.d/plugins folder.

I also tried to pull the source code from this repo and compile the provider. But I got the same error when running terraform plan.

Any idea on what could cause this problem and how to fix it?

Thanks

### PR DESCRIPTION
**Pull request by taiidani**
Running the tf-migrate tool on the codebase and updating documentation. Look at how tiny the go.mod file became!

Fixes #6 

Note that the acceptance test failures have been happening prior to this PR. This has been called out as a separate issue in #9.

### CODE REVIEW

**Comment by taiidani** [comment]
@ttpp8794 would you like to test to confirm that this resolves your issue before it gets merged in?

**Comment by taiidani** [comment]
@ttpp8794 Fixing the acceptance tests involved bumping the upstream Jenkins library. I'm going to ask that you test that #11 PR instead and will merge this in now.

**Comment by ttpp8794** [comment]
@taiidani,  thank you for quick fixing the issue. The provider issue looks get resolved.  Can I use the latest changes in master branch now or should I wait until you fix the acceptance test issue?

**Comment by taiidani** [comment]
@ttpp8794 Thankfully fixing the acceptance test was as simple as upgrading the upstream library (#11), so it should be good to go in `master` now! I have also tagged 0.4.0 in case consumers prefer pinning to semver tags.

**Pull request merged**
