### PR TITLE
Adding jenkins_credential_username resource

### PR DESCRIPTION
**Pull request by taiidani**
# Dependencies

Contributes to #13 

# What Is Changing

Adding a new `jenkins_credential_username` source, supporting the "username" credentials type.

# Test Steps

```sh
make testacc
```

### CODE REVIEW

**Comment by davidkarlsen** [comment]
I tried to `make install` the provider, so it ends up in `~/.terraform.d/plugins/` but still when doing `terraform init` it fails:
```
terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/aws v2.70.0
- Using previously-installed hashicorp/github v2.9.2
- Using previously-installed hashicorp/template v2.1.2
- Using previously-installed hashicorp/local v1.4.0
- Finding latest version of hashicorp/jenkins...

Error: Failed to install provider

Error while installing hashicorp/jenkins: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/jenkins

```
any tips?

**Comment by davidkarlsen** [comment]
Should it work with TF 0.13?

**Comment by davidkarlsen** [comment]
Could you push the updated version? No matter what I try to get the locally installed provider TF won't play along.

**Comment by taiidani** [comment]
@davidkarlsen It looks like 0.13 [changes a lot of things](https://www.terraform.io/upgrade-guides/0-13.html) around for providers, including [adding a new `required_providers` line](https://github.com/taiidani/terraform-provider-jenkins/blob/master/example/providers.tf#L10-L17) in order to locate a community provider within the registry.

It also changes the locations of plugins on-disk so I'm going to need to figure out how to get the `makefile` working for the new layout...hmm.

I had success with the following for 0.13 on macOS:

```
BINARY=terraform-provider-jenkins_v0.5.0

default: build

# Builds the provider and adds it to the example Terraform installation.
build:
	go build -o "example/.terraform/plugins/registry.terraform.io/taiidani/jenkins/0.5.0/darwin_amd64/${BINARY}"
	cd example && terraform init && terraform validate
```

And then a `make build`. Replace the relative path with the path to your Terraform installation.

**Comment by davidkarlsen** [comment]
I tried that, no cigar.
Can you try the following provider setup:
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 2.34"
    }
    github = {
      source  = "hashicorp/github"
      version = "~> 2.9.2"
    }
    jenkinscredentials = {
      source = "somefakedomain.com/taiidani/jenkins"
      version = "= 0.6.0" // I made it this version to avoid clashing with 0.5.0 in the registry
    }
  }
  required_version = ">= 0.13"
}

provider "jenkinscredentials" {
  server_url = "https://somejenkins.acme.org/"
  username   = "somuser"
  password   = "somepw"
}
```

Still:

```
nitializing provider plugins...
- Using previously-installed somefakedomain.com/taiidani/jenkins v0.6.0
- Using previously-installed hashicorp/aws v2.70.0
- Using previously-installed hashicorp/template v2.1.2
- Using previously-installed hashicorp/local v1.4.0
- Using previously-installed hashicorp/github v2.9.2
- Finding latest version of hashicorp/jenkins...

Error: Failed to install provider

Error while installing hashicorp/jenkins: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/jenkins
```

```
ls -l ~/.terraform.d/plugins/somefakedomain.com/taiidani/jenkins/0.6.0/darwin_amd64/terraform-provider-jenkins_v0.6.0 
-rwxr-xr-x  1 et2448  staff  19896004 Aug 18 13:48 /Users/et2448/.terraform.d/plugins/somefakedomain.com/taiidani/jenkins/0.6.0/darwin_amd64/terraform-provider-jenkins_v0.6.0
```

**Comment by taiidani** [comment]
Hmm, from my understanding of the new `required_providers` block, the provider locations _need_ to point at something pre-existing. So `somefakedomain.com` won't work unless you wade into the ugly waters of `filesystem_mirrors`.

The strategy I've been using is to `init`, replace the binary it downloaded, then `init` again.

So for the [example folder](https://github.com/taiidani/terraform-provider-jenkins/tree/master/example) you would:

```sh
cd ./example

# Simulate Jenkins, or have an accessible Jenkins installation to test against
docker-compose up -d 

# Download the 0.5.0 binary from the registry
terraform init

# Back to root directory to replace the binary
cd ../ 
go build -o "example/.terraform/plugins/registry.terraform.io/taiidani/jenkins/0.5.0/darwin_amd64/terraform-provider-jenkins_v0.5.0"

# And finally back to the example to work normally
cd example
terraform init
terraform plan
```

Very sorry about the trouble testing this. I've opened up an issue against the Terraform repo reporting the breaking changes around local provider development: https://github.com/hashicorp/terraform/issues/25906.

If we go through another cycle with problems I'll plan to just add "this is experimental" wording to the docs for the new resource and release as-is.

**Comment by davidkarlsen** [comment]
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 2.34"
    }
    github = {
      source  = "hashicorp/github"
      version = "~> 2.9.2"
    }
    jenkinscredentials = {
      source = "taiidani/jenkins"
      version = "= 0.5.0"
    }
  }
  required_version = ">= 0.13"
}
```

```
terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed taiidani/jenkins v0.5.0
- Using previously-installed hashicorp/aws v2.70.0
- Using previously-installed hashicorp/github v2.9.2
- Using previously-installed hashicorp/template v2.1.2
- Using previously-installed hashicorp/local v1.4.0
- Finding latest version of hashicorp/jenkins...

Error: Failed to install provider

Error while installing hashicorp/jenkins: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/jenkins
```

**Comment by taiidani** [comment]
Do you have a `provider "jenkins"` line lying around in your installation? Your `required_providers` is providing the location of the `jenkinscredentials` provider (the alias your block sets it to) but it looks like there's another provider set to the `jenkins` alias in the mix. Terraform is trying to find the location for that provider, not finding it in `required_providers`, and then defaulting to the TF 0.12 assumption that the provider is owned by Hashicorp.

Noting:

```
- Using previously-installed taiidani/jenkins v0.5.0
- Finding latest version of hashicorp/jenkins...
```

^ It's trying to find it twice, leading to my theory.

**Comment by davidkarlsen** [comment]
I copied it in manually:
```
s -l .terraform/plugins/registry.terraform.io/taiidani/jenkins/0.5.0/darwin_amd64/terraform-provider-jenkins_v0.5.0 
-rwxr-xr-x  1 et2448  staff  19896004 Aug 19 20:23 .terraform/plugins/registry.terraform.io/taiidani/jenkins/0.5.0/darwin_amd64/terraform-provider-jenkins_v0.5.0
```

**Comment by davidkarlsen** [comment]
It seems configuring the provider (server, user, pw) is the problematic part - if I leave that out and conf via env-vars it passes.

**Comment by davidkarlsen** [comment]
```
2020/08/19 20:59:39 [WARN] Provider "registry.terraform.io/hashicorp/jenkins" produced an invalid plan for module.ecr["test"].jenkins_credential_username.jenkins_credentials, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .scope: planned value cty.StringVal("GLOBAL") does not match config value cty.NullVal(cty.String)
      - .description: planned value cty.StringVal("Managed by Terraform") does not match config value cty.NullVal(cty.String)
      - .domain: planned value cty.StringVal("_") does not match config value cty.NullVal(cty.String)
module.ecr["test"].jenkins_credential_username.jenkins_credentials: Creating...
2020/08/19 20:59:39 [DEBUG] EvalApply: ProviderMeta config value set
2020/08/19 20:59:39 [DEBUG] module.ecr["test"].jenkins_credential_username.jenkins_credentials: applying the planned Create change
2020/08/19 20:59:39 [DEBUG] module.ecr["test"].jenkins_credential_username.jenkins_credentials: apply errored, but we're indicating that via the Error pointer rather than returning it: Could not create username credentials: invalid response code 404
2020/08/19 20:59:39 [ERROR] eval: *terraform.EvalApplyPost, err: Could not create username credentials: invalid response code 404
2020/08/19 20:59:39 [ERROR] eval: *terraform.EvalSequence, err: Could not create username credentials: invalid response code 404

Error: Could not create username credentials: invalid response code 404


Releasing state lock. This may take a few moments...
2020-08-19T20:59:40.199+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
```

**Comment by davidkarlsen** [comment]
If I leave out folder it passes.

**Comment by taiidani** [comment]
`invalid response code 404` is the best I get from the underlying client library which is...only a little helpful. I'm going to assume it was something with the folder name and added a pre-create check against that property. Hopefully that makes the error message a little nicer!

Also going to merge and tag this. I'm on vacation so not sure how quickly I'll be able to get the other credentials types, but I'll try!

**Pull request merged**
