### PR TITLE
Applying consistent folder name formatting to Credentials

### PR DESCRIPTION
**Pull request by taiidani**
# Breaking Changes

This changes the internal `id` attribute of Jobs and Credentials to closer align with their canonical URLs within Jenkins. When updating to this version you will need to `rm` and `import` any existing Jobs, Folders, or Credentials in your state files in order to update their Ids.

Additionally, this changes how folders are specified in Jobs and Folders. There is now an explicit "Folder" property where you can specify the folder name, or in the case of folders the parent folder(s) name. A validation has been added to the "Name" property that will guide users away from using it for folder structures.

# Dependencies

Comparison PR against #20 

# What Is Changing

A slightly different take on @Otterian's #20 PR (with their commit cherry-picked in to preserve credit). I was having difficulty writing acceptance tests without requiring a `depends_on` check (or a "replace / with /job/" transform) so I tried a different tact of getting `formatJobName()` to support _both_ `folder` properties with "job" in them and without.

Example of how it may have worked without `formatJobName()`:

```tf
resource jenkins_folder foo {
  name = "testing-subfolder"
}

resource jenkins_folder foo2 {
  name = "${jenkins_folder.foo.name}/deeper"
}

resource jenkins_credential_username foo {
  name     = "test-username"
  folder   = replace(jenkins_folder.foo2.name, "/", "/job/")
  username = "foo"
  password = "bar"
}

# OR

resource jenkins_credential_username foo {
  depends_on = [jenkins_folder.foo2]
  name     = "test-username"
  folder   = "testing-subfolder/job/deeper"
  username = "foo"
  password = "bar"
}
```

That method _should_ work with this implementation as well, but this implementation also supports a direct dependency:

```tf
resource jenkins_credential_username foo {
  name     = "test-username"
  folder   = jenkins_folder.foo2.name
  username = "foo"
  password = "bar"
}
```

# Test Steps

```sh
make testacc
```

I'd love @Otterian's opinion on this strategy! I'll admit there was a period in the middle of this where I was ripping my hair out :)

### CODE REVIEW

**Comment by Otterian** [comment]
One question - why support both folder properties? AFAIK any folder in Jenkins is prepended by /job/, unless you're in the top-level.

I admit it feels unnecessary to do this on the provider level, as this should probably be handled by the Jenkins Go API client the provider is using. As far as I can see, there it only prepends "job" to the beginning, but there could be **n** depth.
For instance -> http://127.0.0.1:8080/job/test1/job/test2/job/test3/ Which would be 3 layers deep.
Looks good otherwise, though - but do take my advice with a grain of salt, I'm in no way proficient enough in Go to be an authority on the matter :)

**Comment by taiidani** [comment]
For what it's worth, this is my first public-facing Terraform provider myself so there's some teething going on in my designs :)

The trick around this is that Folders are an optional plugin in Jenkins, so the Jenkins Go API library is [mostly] built folder-agnostic. The library has a couple places where it has exposed folder logic but it's not comprehensive. For my Terraform provider I was trying to build it folder-first based on the experiences I've had using Jenkins...but that may have been a bad assumption to make for an OSS provider.

That said, while it will introduce more edge cases for my provider to deal with (and thus potential bugs) I think the outcome of having end-users have a choice of specifying `/job/` or not in their paths would be a nice convenience for them?

...thinking about this further, I might want to make a breaking change where the internal state `id` uses the `/job/` format, and then use my personal format (`/job/` excluded) as a separate resource output. That way `id` matches the canonical format that Jenkins wants, the output allows for the human-readable structure, and the provider will deal with the sometimes-supported-sometimes-not folder naming quirks of the underlying Jenkins Go API library.

**Comment by davidkarlsen** [comment]
Can you create a release please?

**Comment by Otterian** [comment]
Please don't create a new release yet. This doesn't work as intended to create credentials scoped to a nested folder.

The formatFolderName function breaks this. Jenkins expects an initial "/job" when dealing with folders and/or jobs in nested folders.

Let's say if I pass "/job/test/job/testsub/job/testsub/" to the formatFolderName function, it will return "test/job/testsub/job/testsubsub". The first "/job" is stripped/ignored and the resulting string is passed to resourceJenkinsCredentialUsernameCreate and subsequently causes Terraform to err out because the folder/job simply doesn't exist in Jenkins (404).

**Comment by Otterian** [comment]
Imo I think it's better to get rid of the formatFolderName function and just pass the string in its entirety to the provider. Mostly because IaC is a source of truth, and if the provider is changing any of the truth when applying, then it's no longer a source of truth, in my opinion. 

It's less intrusive if the provider can e.g just return an error telling the user that the formatting of the string is wrong.

**Comment by taiidani** [comment]
@davidkarlsen I released 0.7.0-beta1 yesterday which includes these changes for testing purposes. Oddly the Terraform Registry didn't recognize this as a pre-release and has it listed as an initial release...

As noted in the [release notes](https://github.com/taiidani/terraform-provider-jenkins/releases/tag/v0.7.0-beta1) and alluded to by @Otterian there are **multiple breaking changes** in how IDs are stored that may require existing installs to recreate their jobs. It's highly recommended to use the `id` output of the `jenkins_folder` resource as the input to your `folder` property; this will also let Terraform know about the dependency chain.

**Comment by taiidani** [comment]
@Otterian I don't disagree and that's essentially where 0.7.0 is headed. All internal IDs are now the canonical versions, anything with `formatFolderName` is converted to the canonical format on the subsequent `Read` call, and the `folder` property itself only functions properly with folder names in the canonical format. Was there something else you were raising issue on?

That said, emphasis on Beta! There have been plumbing changes internally (both in-provider and in the TF SDK) and I still have a couple more feature requests to finish; I'm not confident that the provider is bug free.

**Pull request merged**
