### PR TITLE
Fixed folder validation check

### PR DESCRIPTION
**Pull request by Otterian**
# Dependencies

None beyond what is already included in the source.

# What Is Changing

Error checking when creating a new Jenkins credentials

# Test Steps

```sh
make testacc
```

### CODE REVIEW

**Comment by Otterian** [comment]
Fixes https://github.com/taiidani/terraform-provider-jenkins/issues/13#issuecomment-682399802

**Comment by Otterian** [comment]
Hi,

Any reason why this is not merged into master yet?

Thanks.

**Comment by taiidani** [comment]
Sorry @Otterian! I just haven't had the time to do a proper review & merge. I'll try to carve out time this weekend.

**Comment by taiidani** [comment]
HI @Otterian. I tried building some acceptance tests around your use case here (nested subfolders) but had quite a bit of trouble getting the full create+update+destroy cycle to work, especially while trying to avoid adding explicit `depends_on` properties to avoid race conditions.

I cherry-picked your commit into #21 which takes a slightly different approach. I'd really appreciate your feedback! If we can get your proposal of removing `formatJobName` to work with the tests then I'd happily accept that change as it would simplify the implementation.

**Comment by taiidani** [comment]
Merged #21 which should [I hope] address the items brought up in this PR. I'll be prepping it alongside other updates in the 0.7 release, which will include breaking changes.

**Pull request closed without merging**
